#!/bin/bash

# Inertia React App currently in different repo to simplify distribution
git clone git@github.com:backlineint/drupal-inertia-react-app.git web/modules/custom/inertia_examples/app

ddev start
ddev composer install
ddev drush site:install -y

# Install a small amount of dependencies
ddev drush en inertia_examples devel_generate -y

# Generate some content
ddev drush devel-generate:content

# Build production version of Inertia app
ddev npm install --prefix web/modules/custom/inertia_examples/app
ddev npm run build --prefix web/modules/custom/inertia_examples/app

# You know, caches
ddev drush cr

# Open Drupal in browser
ddev drush uli | xargs open

